package application.enums;

public enum LoginProcessEnum {
    PREPAIRING_TO_GET_DATA_FROM_INPUT,
    GETTING_DATA_FROM_INPUT,
    VALIDATING_DATA,
    VALIDATION_SUCESS,
    // EXCEPTIONS
    GET_DATA_FAILED,
    VALIDATION_FAILED,
    EXPIRED_TIME;
}
