package application.enums;
public enum Process{
    // MAIN PROCESS
    PREPAIRING_TO_GET_DATA_FROM_INPUT,
    GETTING_DATA_FROM_INPUT,
    VALIDATING_DATA,
    VALIDATION_SUCESS,
    SENDING_CONFIRMATION_EMAIL,
    CONFIRMATION_EMAIL_ARRIVED,
    WAITING_CONFIRMATION_CODE,
    EMAIL_CONFIRMED,

    // EXCEPTIONS
    GET_DATA_FAILED,
    VALIDATION_FAILED,
    EMAIL_NOT_ARRIVED_TO_DESTINATION,
    INVALID_CODE,
    EXPIRED_TIME;
}
