package application.enums;
public enum Process{
    // MAIN PROCESS
    PREPAIRING_TO_GET_DATA_FROM_INPUT,
    GETTING_DATA_FROM_INPUT,
    VALIDATING_DATA,
    VALIDATION_SUCESS,
    SENDING_CONFIRMATION_EMAIL,
    CONFIRMATING_EMAIL_ARRIVED,
    EMAIL_CONFIRMED,

    // EXCEPTIONS
    GET_DATA_FAILED,
    VALIDATION_FAILED,
    EMAIL_NOT_ARRIVED_TO_DESTINATION,
    EXPIRED_TIME,
    EMAIL_CONFIRMATION_DENIED_BY_OWNER;
}
