package application.enums;
public enum Register{
    // MAIN PROCESS
    GETTING_DATA,
    VALIDATING_DATA,
    SENDING_CONFIRMATION_EMAIL,
    CONFIRMATING_EMAIL_ARRIVED,
    EMAIL_CONFIRMED,

    // EXCEPTIONS
    EXPIRED_TIME,
    EMAIL_CONFIRMATION_DENIED_BY_OWNER;
}
